<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.df4j.xctec.xcms</groupId>
        <artifactId>xcms</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>xcms-tenant-management</artifactId>
    <packaging>pom</packaging>
    <name>XCMS Tenant Parent</name>
    <modules>
        <module>xcms-tenant-api</module>
        <module>xcms-tenant-impl</module>
    </modules>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
